id: 561e4f86e73f4dc191a7165f4b8341cf
initial_creation_type: ocr
source_metadata:
  volumes:
    09ee4b3d995f40d587c3a674a584758f:
      base_file: v026.txt
      image_group_id: I1PD95871
      title: མཎྜལ་གྱི་ཆོ་ག།
      total_pages: 1902
      volume_number: 26
